package entities;
// Generated Apr 29, 2016 4:28:59 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BangluongId generated by hbm2java
 */
@Embeddable
public class BangluongId implements java.io.Serializable {

	private int id;
	private Serializable maLuong;
	private Serializable maCa;
	private Serializable maViTri;
	private Serializable dienGiai;
	private BigDecimal tienLuongNgay;
	private boolean status;
	private Serializable createdBy;
	private Date createdDate;
	private Serializable updatedBy;
	private Date updatedDate;

	public BangluongId() {
	}

	public BangluongId(int id, Serializable maLuong, Serializable maCa, Serializable maViTri, Serializable dienGiai,
			BigDecimal tienLuongNgay, boolean status, Serializable createdBy, Date createdDate, Serializable updatedBy,
			Date updatedDate) {
		this.id = id;
		this.maLuong = maLuong;
		this.maCa = maCa;
		this.maViTri = maViTri;
		this.dienGiai = dienGiai;
		this.tienLuongNgay = tienLuongNgay;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MaLuong", nullable = false)
	public Serializable getMaLuong() {
		return this.maLuong;
	}

	public void setMaLuong(Serializable maLuong) {
		this.maLuong = maLuong;
	}

	@Column(name = "MaCa", nullable = false)
	public Serializable getMaCa() {
		return this.maCa;
	}

	public void setMaCa(Serializable maCa) {
		this.maCa = maCa;
	}

	@Column(name = "MaViTri", nullable = false)
	public Serializable getMaViTri() {
		return this.maViTri;
	}

	public void setMaViTri(Serializable maViTri) {
		this.maViTri = maViTri;
	}

	@Column(name = "DienGiai", nullable = false)
	public Serializable getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(Serializable dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "TienLuongNgay", nullable = false, scale = 4)
	public BigDecimal getTienLuongNgay() {
		return this.tienLuongNgay;
	}

	public void setTienLuongNgay(BigDecimal tienLuongNgay) {
		this.tienLuongNgay = tienLuongNgay;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BangluongId))
			return false;
		BangluongId castOther = (BangluongId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getMaLuong() == castOther.getMaLuong()) || (this.getMaLuong() != null
						&& castOther.getMaLuong() != null && this.getMaLuong().equals(castOther.getMaLuong())))
				&& ((this.getMaCa() == castOther.getMaCa()) || (this.getMaCa() != null && castOther.getMaCa() != null
						&& this.getMaCa().equals(castOther.getMaCa())))
				&& ((this.getMaViTri() == castOther.getMaViTri()) || (this.getMaViTri() != null
						&& castOther.getMaViTri() != null && this.getMaViTri().equals(castOther.getMaViTri())))
				&& ((this.getDienGiai() == castOther.getDienGiai()) || (this.getDienGiai() != null
						&& castOther.getDienGiai() != null && this.getDienGiai().equals(castOther.getDienGiai())))
				&& ((this.getTienLuongNgay() == castOther.getTienLuongNgay())
						|| (this.getTienLuongNgay() != null && castOther.getTienLuongNgay() != null
								&& this.getTienLuongNgay().equals(castOther.getTienLuongNgay())))
				&& (this.isStatus() == castOther.isStatus())
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())))
				&& ((this.getUpdatedDate() == castOther.getUpdatedDate())
						|| (this.getUpdatedDate() != null && castOther.getUpdatedDate() != null
								&& this.getUpdatedDate().equals(castOther.getUpdatedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getMaLuong() == null ? 0 : this.getMaLuong().hashCode());
		result = 37 * result + (getMaCa() == null ? 0 : this.getMaCa().hashCode());
		result = 37 * result + (getMaViTri() == null ? 0 : this.getMaViTri().hashCode());
		result = 37 * result + (getDienGiai() == null ? 0 : this.getDienGiai().hashCode());
		result = 37 * result + (getTienLuongNgay() == null ? 0 : this.getTienLuongNgay().hashCode());
		result = 37 * result + (this.isStatus() ? 1 : 0);
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result + (getUpdatedDate() == null ? 0 : this.getUpdatedDate().hashCode());
		return result;
	}

}
