package entities;
// Generated May 5, 2016 9:29:35 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bangluong generated by hbm2java
 */
@Entity
@Table(name = "BANGLUONG", catalog = "RMS")
public class Bangluong implements java.io.Serializable {

	private BangluongId id;

	public Bangluong() {
	}

	public Bangluong(BangluongId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "maLuong", column = @Column(name = "MaLuong", nullable = false)),
			@AttributeOverride(name = "maCa", column = @Column(name = "MaCa", nullable = false)),
			@AttributeOverride(name = "maViTri", column = @Column(name = "MaViTri", nullable = false)),
			@AttributeOverride(name = "dienGiai", column = @Column(name = "DienGiai", nullable = false)),
			@AttributeOverride(name = "tienLuongNgay", column = @Column(name = "TienLuongNgay", nullable = false, scale = 4)),
			@AttributeOverride(name = "status", column = @Column(name = "Status", nullable = false)),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CreatedBy", nullable = false)),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CreatedDate", nullable = false, length = 23)),
			@AttributeOverride(name = "updatedBy", column = @Column(name = "UpdatedBy", nullable = false)),
			@AttributeOverride(name = "updatedDate", column = @Column(name = "UpdatedDate", nullable = false, length = 23)) })
	public BangluongId getId() {
		return this.id;
	}

	public void setId(BangluongId id) {
		this.id = id;
	}

}
