package entities;
// Generated May 5, 2016 4:52:51 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calamviec generated by hbm2java
 */
@Entity
@Table(name = "CALAMVIEC", catalog = "RMS")
public class Calamviec implements java.io.Serializable {

	private String maCa;
	private String tenCa;
	private String dienGiai;
	private Date batDau;
	private Date ketThuc;
	private boolean status;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private int nhanVienToiThieu;
	private int nhanVienToiDa;

	public Calamviec() {
	}

	public Calamviec(String maCa, String tenCa, String dienGiai, Date batDau, Date ketThuc,
			boolean status, String createdBy, Date createdDate, String updatedBy, Date updatedDate,
			int nhanVienToiThieu, int nhanVienToiDa) {
		this.maCa = maCa;
		this.tenCa = tenCa;
		this.dienGiai = dienGiai;
		this.batDau = batDau;
		this.ketThuc = ketThuc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.nhanVienToiThieu = nhanVienToiThieu;
		this.nhanVienToiDa = nhanVienToiDa;
	}

	@Id

	@Column(name = "MaCa", unique = true, nullable = false)
	public String getMaCa() {
		return this.maCa;
	}

	public void setMaCa(String maCa) {
		this.maCa = maCa;
	}

	@Column(name = "TenCa", nullable = false)
	public String getTenCa() {
		return this.tenCa;
	}

	public void setTenCa(String tenCa) {
		this.tenCa = tenCa;
	}

	@Column(name = "DienGiai", nullable = false)
	public String getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(String dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "BatDau", nullable = false, length = 14)
	public Date getBatDau() {
		return this.batDau;
	}

	public void setBatDau(Date batDau) {
		this.batDau = batDau;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "KetThuc", nullable = false, length = 14)
	public Date getKetThuc() {
		return this.ketThuc;
	}

	public void setKetThuc(Date ketThuc) {
		this.ketThuc = ketThuc;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "NhanVienToiThieu", nullable = false)
	public int getNhanVienToiThieu() {
		return this.nhanVienToiThieu;
	}

	public void setNhanVienToiThieu(int nhanVienToiThieu) {
		this.nhanVienToiThieu = nhanVienToiThieu;
	}

	@Column(name = "NhanVienToiDa", nullable = false)
	public int getNhanVienToiDa() {
		return this.nhanVienToiDa;
	}

	public void setNhanVienToiDa(int nhanVienToiDa) {
		this.nhanVienToiDa = nhanVienToiDa;
	}

}
