package entities;
// Generated Apr 29, 2016 4:28:59 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Calamviec generated by hbm2java
 */
@Entity
@Table(name = "CALAMVIEC", catalog = "RMS")
public class Calamviec implements java.io.Serializable {

	private Serializable maCa;
	private int id;
	private Serializable tenCa;
	private Serializable dienGiai;
	private Date batDau;
	private Date ketThuc;
	private boolean status;
	private Serializable createdBy;
	private Date createdDate;
	private Serializable updatedBy;
	private Date updatedDate;

	public Calamviec() {
	}

	public Calamviec(Serializable maCa, int id, Serializable tenCa, Serializable dienGiai, Date batDau, Date ketThuc,
			boolean status, Serializable createdBy, Date createdDate, Serializable updatedBy, Date updatedDate) {
		this.maCa = maCa;
		this.id = id;
		this.tenCa = tenCa;
		this.dienGiai = dienGiai;
		this.batDau = batDau;
		this.ketThuc = ketThuc;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "MaCa", unique = true, nullable = false)
	public Serializable getMaCa() {
		return this.maCa;
	}

	public void setMaCa(Serializable maCa) {
		this.maCa = maCa;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenCa", nullable = false)
	public Serializable getTenCa() {
		return this.tenCa;
	}

	public void setTenCa(Serializable tenCa) {
		this.tenCa = tenCa;
	}

	@Column(name = "DienGiai", nullable = false)
	public Serializable getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(Serializable dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "BatDau", nullable = false, length = 14)
	public Date getBatDau() {
		return this.batDau;
	}

	public void setBatDau(Date batDau) {
		this.batDau = batDau;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "KetThuc", nullable = false, length = 14)
	public Date getKetThuc() {
		return this.ketThuc;
	}

	public void setKetThuc(Date ketThuc) {
		this.ketThuc = ketThuc;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
