package entities;
// Generated May 7, 2016 10:00:00 AM by Hibernate Tools 5.1.0.Alpha1

import java.io.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chamcong generated by hbm2java
 */
@Entity
@Table(name = "CHAMCONG", catalog = "RMS")
public class Chamcong implements java.io.Serializable {

	private int maChamCong;
	private String maNguoiDung;
	private String maCa;
	private int ngay;
	private int thang;
	private int nam;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String dienGiai;

	public Chamcong() {
	}

	public Chamcong(int maChamCong, String maNguoiDung, String maCa, int ngay, int thang, int nam,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate, String dienGiai) {
		this.maChamCong = maChamCong;
		this.maNguoiDung = maNguoiDung;
		this.maCa = maCa;
		this.ngay = ngay;
		this.thang = thang;
		this.nam = nam;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.dienGiai = dienGiai;
	}

	@Id
	@GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
	@Column(name = "MaChamCong", unique = true, nullable = true)
	public int getMaChamCong() {
		return this.maChamCong;
	}

	public void setMaChamCong(int maChamCong) {
		this.maChamCong = maChamCong;
	}

	@Column(name = "MaNguoiDung", nullable = false)
	public String getMaNguoiDung() {
		return this.maNguoiDung;
	}

	public void setMaNguoiDung(String maNguoiDung) {
		this.maNguoiDung = maNguoiDung;
	}

	@Column(name = "MaCa", nullable = false)
	public String getMaCa() {
		return this.maCa;
	}

	public void setMaCa(String maCa) {
		this.maCa = maCa;
	}

	@Column(name = "Ngay", nullable = false)
	public int getNgay() {
		return this.ngay;
	}

	public void setNgay(int ngay) {
		this.ngay = ngay;
	}

	@Column(name = "Thang", nullable = false)
	public int getThang() {
		return this.thang;
	}

	public void setThang(int thang) {
		this.thang = thang;
	}

	@Column(name = "Nam", nullable = false)
	public int getNam() {
		return this.nam;
	}

	public void setNam(int nam) {
		this.nam = nam;
	}

	@Column(name = "CreatedBy", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "DienGiai", nullable = false)
	public String getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(String dienGiai) {
		this.dienGiai = dienGiai;
	}

}
