package entities;
// Generated May 7, 2016 3:58:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chitiethoadon generated by hbm2java
 */
@Entity
@Table(name = "CHITIETHOADON", catalog = "RMS")
public class Chitiethoadon implements java.io.Serializable {

	private int id;
	private Serializable maHd;
	private Serializable maThucDon;
	private Serializable ghiChu;
	private int gia;
	private boolean status;
	private Serializable createdBy;
	private Date createdDate;
	private Serializable updatedBy;
	private Date updatedDate;

	public Chitiethoadon() {
	}

	public Chitiethoadon(int id, Serializable maHd, Serializable maThucDon, Serializable ghiChu, int gia,
			boolean status, Serializable createdBy, Date createdDate, Serializable updatedBy, Date updatedDate) {
		this.id = id;
		this.maHd = maHd;
		this.maThucDon = maThucDon;
		this.ghiChu = ghiChu;
		this.gia = gia;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MaHD", nullable = false)
	public Serializable getMaHd() {
		return this.maHd;
	}

	public void setMaHd(Serializable maHd) {
		this.maHd = maHd;
	}

	@Column(name = "MaThucDon", nullable = false)
	public Serializable getMaThucDon() {
		return this.maThucDon;
	}

	public void setMaThucDon(Serializable maThucDon) {
		this.maThucDon = maThucDon;
	}

	@Column(name = "GhiChu", nullable = false)
	public Serializable getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(Serializable ghiChu) {
		this.ghiChu = ghiChu;
	}

	@Column(name = "Gia", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
