package entities;
// Generated May 10, 2016 4:19:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.*;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chitiethoadon generated by hbm2java
 */
@Entity
@Table(name = "CHITIETHOADON", catalog = "RMS")
public class Chitiethoadon implements java.io.Serializable {

	private int id;
	private String maHd;
	private String maThucDon;
	private String ghiChu;
	private int soLuong;
	private int gia;
	private boolean status;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public Chitiethoadon() {
	}

	public Chitiethoadon(int id, String maHd, String maThucDon, String ghiChu, int soLuong, int gia,
			boolean status, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
		this.id = id;
		this.maHd = maHd;
		this.maThucDon = maThucDon;
		this.ghiChu = ghiChu;
		this.soLuong = soLuong;
		this.gia = gia;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MaHD", nullable = false)
	public String getMaHd() {
		return this.maHd;
	}

	public void setMaHd(String maHd) {
		this.maHd = maHd;
	}

	@Column(name = "MaThucDon", nullable = false)
	public String getMaThucDon() {
		return this.maThucDon;
	}

	public void setMaThucDon(String maThucDon) {
		this.maThucDon = maThucDon;
	}

	@Column(name = "GhiChu", nullable = false)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "Gia", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
