package entities;
// Generated Apr 28, 2016 7:02:44 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name = "NGUOIDUNG", catalog = "RMS")
public class Nguoidung implements java.io.Serializable {

	private String maNguoiDung;
	private String cmnd;
	private String createdBy;
	private Date createdDate;
	private String diaChi;
	private String dienGiai;
	private String dienThoai;
	private boolean gioiTinh;
	private String maTrinhDo;
	private String maViTri;
	private String matKhau;
	private Date ngaySinh;
	private boolean status;
	private String tenNguoiDung;
	private String updatedBy;
	private Date updatedDate;

	public Nguoidung() {
	}

	public Nguoidung(String maNguoiDung, String cmnd, String createdBy, Date createdDate,
			String diaChi, String dienGiai, String dienThoai, boolean gioiTinh,
			String maTrinhDo, String maViTri, String matKhau, Date ngaySinh, boolean status,
			String tenNguoiDung, String updatedBy, Date updatedDate) {
		this.maNguoiDung = maNguoiDung;
		this.cmnd = cmnd;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.diaChi = diaChi;
		this.dienGiai = dienGiai;
		this.dienThoai = dienThoai;
		this.gioiTinh = gioiTinh;
		this.maTrinhDo = maTrinhDo;
		this.maViTri = maViTri;
		this.matKhau = matKhau;
		this.ngaySinh = ngaySinh;
		this.status = status;
		this.tenNguoiDung = tenNguoiDung;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "MaNguoiDung", unique = true, nullable = false)
	public String getMaNguoiDung() {
		return this.maNguoiDung;
	}

	public void setMaNguoiDung(String maNguoiDung) {
		this.maNguoiDung = maNguoiDung;
	}

	@Column(name = "CMND", nullable = false)
	public String getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(String cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "CreatedBy", nullable = false)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DiaChi", nullable = false)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "DienGiai", nullable = false)
	public String getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(String dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "DienThoai", nullable = false)
	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Column(name = "GioiTinh", nullable = false)
	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "MaTrinhDo", nullable = false)
	public String getMaTrinhDo() {
		return this.maTrinhDo;
	}

	public void setMaTrinhDo(String maTrinhDo) {
		this.maTrinhDo = maTrinhDo;
	}

	@Column(name = "MaViTri", nullable = false)
	public String getMaViTri() {
		return this.maViTri;
	}

	public void setMaViTri(String maViTri) {
		this.maViTri = maViTri;
	}

	@Column(name = "MatKhau", nullable = false)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NgaySinh", nullable = false, length = 23)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "TenNguoiDung", nullable = false)
	public String getTenNguoiDung() {
		return this.tenNguoiDung;
	}

	public void setTenNguoiDung(String tenNguoiDung) {
		this.tenNguoiDung = tenNguoiDung;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
