package entities;
// Generated May 7, 2016 3:58:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nhomthucdon generated by hbm2java
 */
@Entity
@Table(name = "NHOMTHUCDON", catalog = "RMS")
public class Nhomthucdon implements java.io.Serializable {

	private Serializable maNhom;
	private Serializable tenNhom;
	private Serializable dienGiai;
	private boolean status;
	private Serializable createdBy;
	private Date createdDate;
	private Serializable updatedBy;
	private Date updatedDate;

	public Nhomthucdon() {
	}

	public Nhomthucdon(Serializable maNhom, Serializable tenNhom, Serializable dienGiai, boolean status,
			Serializable createdBy, Date createdDate, Serializable updatedBy, Date updatedDate) {
		this.maNhom = maNhom;
		this.tenNhom = tenNhom;
		this.dienGiai = dienGiai;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "MaNhom", unique = true, nullable = false)
	public Serializable getMaNhom() {
		return this.maNhom;
	}

	public void setMaNhom(Serializable maNhom) {
		this.maNhom = maNhom;
	}

	@Column(name = "TenNhom", nullable = false)
	public Serializable getTenNhom() {
		return this.tenNhom;
	}

	public void setTenNhom(Serializable tenNhom) {
		this.tenNhom = tenNhom;
	}

	@Column(name = "DienGiai", nullable = false)
	public Serializable getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(Serializable dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
