package entities;
// Generated May 6, 2016 11:58:11 AM by Hibernate Tools 5.1.0.Alpha1

import java.io.*;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThoigiancothelamviecId generated by hbm2java
 */
@Embeddable
public class ThoigiancothelamviecId implements java.io.Serializable {

	private String maCa;
	private String maNguoiDung;

	public ThoigiancothelamviecId() {
	}

	public ThoigiancothelamviecId(String maCa, String maNguoiDung) {
		this.maCa = maCa;
		this.maNguoiDung = maNguoiDung;
	}

	@Column(name = "MaCa", nullable = false)
	public String getMaCa() {
		return this.maCa;
	}

	public void setMaCa(String maCa) {
		this.maCa = maCa;
	}

	@Column(name = "MaNguoiDung", nullable = false)
	public String getMaNguoiDung() {
		return this.maNguoiDung;
	}

	public void setMaNguoiDung(String maNguoiDung) {
		this.maNguoiDung = maNguoiDung;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThoigiancothelamviecId))
			return false;
		ThoigiancothelamviecId castOther = (ThoigiancothelamviecId) other;

		return ((this.getMaCa() == castOther.getMaCa()) || (this.getMaCa() != null && castOther.getMaCa() != null
				&& this.getMaCa().equals(castOther.getMaCa())))
				&& ((this.getMaNguoiDung() == castOther.getMaNguoiDung())
						|| (this.getMaNguoiDung() != null && castOther.getMaNguoiDung() != null
								&& this.getMaNguoiDung().equals(castOther.getMaNguoiDung())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMaCa() == null ? 0 : this.getMaCa().hashCode());
		result = 37 * result + (getMaNguoiDung() == null ? 0 : this.getMaNguoiDung().hashCode());
		return result;
	}

}
