package entities;
// Generated Apr 28, 2016 7:02:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thoigiancothelamviec generated by hbm2java
 */
@Entity
@Table(name = "THOIGIANCOTHELAMVIEC", catalog = "RMS")
public class Thoigiancothelamviec implements java.io.Serializable {

	private ThoigiancothelamviecId id;
	private byte[] createdBy;
	private Date createdDate;
	private byte[] dienGiai;
	private int id_1;
	private boolean status;
	private byte[] updatedBy;
	private Date updatedDate;

	public Thoigiancothelamviec() {
	}

	public Thoigiancothelamviec(ThoigiancothelamviecId id, byte[] createdBy, Date createdDate, byte[] dienGiai,
			int id_1, boolean status, byte[] updatedBy, Date updatedDate) {
		this.id = id;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.dienGiai = dienGiai;
		this.id_1 = id_1;
		this.status = status;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maCa", column = @Column(name = "MaCa", nullable = false)),
			@AttributeOverride(name = "maNguoiDung", column = @Column(name = "MaNguoiDung", nullable = false)) })
	public ThoigiancothelamviecId getId() {
		return this.id;
	}

	public void setId(ThoigiancothelamviecId id) {
		this.id = id;
	}

	@Column(name = "CreatedBy", nullable = false)
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DienGiai", nullable = false)
	public byte[] getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(byte[] dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "ID", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
