package entities;
// Generated Apr 29, 2016 4:28:59 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thoigiancothelamviec generated by hbm2java
 */
@Entity
@Table(name = "THOIGIANCOTHELAMVIEC", catalog = "RMS")
public class Thoigiancothelamviec implements java.io.Serializable {

	private ThoigiancothelamviecId id;
	private int id_1;
	private Serializable dienGiai;
	private boolean status;
	private Serializable createdBy;
	private Date createdDate;
	private Serializable updatedBy;
	private Date updatedDate;

	public Thoigiancothelamviec() {
	}

	public Thoigiancothelamviec(ThoigiancothelamviecId id, int id_1, Serializable dienGiai, boolean status,
			Serializable createdBy, Date createdDate, Serializable updatedBy, Date updatedDate) {
		this.id = id;
		this.id_1 = id_1;
		this.dienGiai = dienGiai;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maCa", column = @Column(name = "MaCa", nullable = false)),
			@AttributeOverride(name = "maNguoiDung", column = @Column(name = "MaNguoiDung", nullable = false)) })
	public ThoigiancothelamviecId getId() {
		return this.id;
	}

	public void setId(ThoigiancothelamviecId id) {
		this.id = id;
	}

	@Column(name = "ID", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "DienGiai", nullable = false)
	public Serializable getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(Serializable dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
