package entities;
// Generated May 7, 2016 3:58:17 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thucdon generated by hbm2java
 */
@Entity
@Table(name = "THUCDON", catalog = "RMS")
public class Thucdon implements java.io.Serializable {

	private Serializable maThucDon;
	private Serializable tenThucDon;
	private byte[] hinhAnh;
	private Serializable dienGiai;
	private int gia;
	private boolean status;
	private Serializable createdBy;
	private Date createdDate;
	private Serializable updatedBy;
	private Date updatedDate;

	public Thucdon() {
	}

	public Thucdon(Serializable maThucDon, Serializable tenThucDon, Serializable dienGiai, int gia, boolean status,
			Serializable createdBy, Date createdDate, Serializable updatedBy, Date updatedDate) {
		this.maThucDon = maThucDon;
		this.tenThucDon = tenThucDon;
		this.dienGiai = dienGiai;
		this.gia = gia;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	public Thucdon(Serializable maThucDon, Serializable tenThucDon, byte[] hinhAnh, Serializable dienGiai, int gia,
			boolean status, Serializable createdBy, Date createdDate, Serializable updatedBy, Date updatedDate) {
		this.maThucDon = maThucDon;
		this.tenThucDon = tenThucDon;
		this.hinhAnh = hinhAnh;
		this.dienGiai = dienGiai;
		this.gia = gia;
		this.status = status;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "MaThucDon", unique = true, nullable = false)
	public Serializable getMaThucDon() {
		return this.maThucDon;
	}

	public void setMaThucDon(Serializable maThucDon) {
		this.maThucDon = maThucDon;
	}

	@Column(name = "TenThucDon", nullable = false)
	public Serializable getTenThucDon() {
		return this.tenThucDon;
	}

	public void setTenThucDon(Serializable tenThucDon) {
		this.tenThucDon = tenThucDon;
	}

	@Column(name = "HinhAnh")
	public byte[] getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(byte[] hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@Column(name = "DienGiai", nullable = false)
	public Serializable getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(Serializable dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "Gia", nullable = false)
	public int getGia() {
		return this.gia;
	}

	public void setGia(int gia) {
		this.gia = gia;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CreatedBy", nullable = false)
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
