package entities;
// Generated Apr 28, 2016 7:02:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trinhdo generated by hbm2java
 */
@Entity
@Table(name = "TRINHDO", catalog = "RMS")
public class Trinhdo implements java.io.Serializable {

	private byte[] maTrinhDo;
	private byte[] createdBy;
	private Date createdDate;
	private byte[] dienGiai;
	private int id;
	private boolean status;
	private byte[] tenTrinhDo;
	private byte[] updatedBy;
	private Date updatedDate;

	public Trinhdo() {
	}

	public Trinhdo(byte[] maTrinhDo, byte[] createdBy, Date createdDate, byte[] dienGiai, int id, boolean status,
			byte[] tenTrinhDo, byte[] updatedBy, Date updatedDate) {
		this.maTrinhDo = maTrinhDo;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.dienGiai = dienGiai;
		this.id = id;
		this.status = status;
		this.tenTrinhDo = tenTrinhDo;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "MaTrinhDo", unique = true, nullable = false)
	public byte[] getMaTrinhDo() {
		return this.maTrinhDo;
	}

	public void setMaTrinhDo(byte[] maTrinhDo) {
		this.maTrinhDo = maTrinhDo;
	}

	@Column(name = "CreatedBy", nullable = false)
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DienGiai", nullable = false)
	public byte[] getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(byte[] dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "TenTrinhDo", nullable = false)
	public byte[] getTenTrinhDo() {
		return this.tenTrinhDo;
	}

	public void setTenTrinhDo(byte[] tenTrinhDo) {
		this.tenTrinhDo = tenTrinhDo;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
