package entities;
// Generated Apr 28, 2016 7:02:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vitri generated by hbm2java
 */
@Entity
@Table(name = "VITRI", catalog = "RMS")
public class Vitri implements java.io.Serializable {

	private byte[] maViTri;
	private byte[] createdBy;
	private Date createdDate;
	private byte[] dienGiai;
	private int id;
	private boolean status;
	private byte[] tenViTri;
	private byte[] updatedBy;
	private Date updatedDate;

	public Vitri() {
	}

	public Vitri(byte[] maViTri, byte[] createdBy, Date createdDate, byte[] dienGiai, int id, boolean status,
			byte[] tenViTri, byte[] updatedBy, Date updatedDate) {
		this.maViTri = maViTri;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.dienGiai = dienGiai;
		this.id = id;
		this.status = status;
		this.tenViTri = tenViTri;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "MaViTri", unique = true, nullable = false)
	public byte[] getMaViTri() {
		return this.maViTri;
	}

	public void setMaViTri(byte[] maViTri) {
		this.maViTri = maViTri;
	}

	@Column(name = "CreatedBy", nullable = false)
	public byte[] getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(byte[] createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "DienGiai", nullable = false)
	public byte[] getDienGiai() {
		return this.dienGiai;
	}

	public void setDienGiai(byte[] dienGiai) {
		this.dienGiai = dienGiai;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "TenViTri", nullable = false)
	public byte[] getTenViTri() {
		return this.tenViTri;
	}

	public void setTenViTri(byte[] tenViTri) {
		this.tenViTri = tenViTri;
	}

	@Column(name = "UpdatedBy", nullable = false)
	public byte[] getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(byte[] updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", nullable = false, length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
